version: '2'

services:
  pg:
    image: docker.io/bitnami/postgresql:11
    env_file:
      - database.env
    ports:
      - '5444:5432'
    expose:
            - '5444'
    volumes:
      - 'pg_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
  mysql:
    #optional to define version (e.g 5.7)
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_staging'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user_aldy'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3314:3306'
    expose:
      # Opens port 3306 on the container
      - '3314'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
volumes:
  pg_data:
    driver: local
  my-db:
    driver: local
